Data cleaning for indian_movies dataset

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/home/nineleaps/Python_training/Trainer_Assignment/indian_movies.csv')
df.head()

,Unnamed: 0,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
0,7,MOV008,Sarkar (Tamil),A. R. Murugadoss,Action Thriller,2005.0,NaN,NaN,7.5,173.0,Vijay,Keerthy Suresh,Tamil,Kalaignar TV
1,9,MOV010,2.0 (Tamil),S. Shankar,Science Fiction Action,2018.0,550.0,800.0,6.9,147.0,Rajinikanth,Amy Jackson,Tamil,Lyca Productions
2,21,MOV022,K.G.F: Chapter 1,Prashanth Neel,Action Drama,2018.0,50.0,250.0,7.9,156.0,Yash,Srinidhi Shetty,Kannada,Hombale Films
3,23,MOV024,Avengers: Endgame (Dubbed),"Anthony Russo, Joseph Russo",Superhero,2019.0,NaN,NaN,8.4,181.0,Robert Downey Jr.,Scarlett Johansson,"English (Dubbed in Telugu, Kannada, Hindi)",Marvel Studios
4,25,MOV026,Pailwaan,S. Krishna,Sports Action,2019.0,30.0,55.0,6.8,NaN,Sudeep,Aakanksha Singh,Kannada,RRR Motion Pictures

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          18 non-null     int64
 1   MovieID             18 non-null     object
 2   Title               18 non-null     object
 3   Director            18 non-null     object
 4   Genre               18 non-null     object
 5   ReleaseYear         17 non-null     float64
 6   Budget (Crores)     10 non-null     float64
 7   BoxOffice (Crores)  10 non-null     float64
 8   Rating              17 non-null     float64
 9   Duration (minutes)  17 non-null     float64
 10  LeadActor           18 non-null     object
 11  LeadActress         18 non-null     object
 12  Language            18 non-null     object
 13  ProductionCompany   18 non-null     object
dtypes: float64(5), int64(1), object(8)
memory usage: 2.1+ KB

In [5]:
# since the column 1 is unnamed i am naming as index as per previous dataset

df.rename(columns={'Unnamed: 0': 'index'}, inplace=True)
df.head()

,index,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
0,7,MOV008,Sarkar (Tamil),A. R. Murugadoss,Action Thriller,2005.0,NaN,NaN,7.5,173.0,Vijay,Keerthy Suresh,Tamil,Kalaignar TV
1,9,MOV010,2.0 (Tamil),S. Shankar,Science Fiction Action,2018.0,550.0,800.0,6.9,147.0,Rajinikanth,Amy Jackson,Tamil,Lyca Productions
2,21,MOV022,K.G.F: Chapter 1,Prashanth Neel,Action Drama,2018.0,50.0,250.0,7.9,156.0,Yash,Srinidhi Shetty,Kannada,Hombale Films
3,23,MOV024,Avengers: Endgame (Dubbed),"Anthony Russo, Joseph Russo",Superhero,2019.0,NaN,NaN,8.4,181.0,Robert Downey Jr.,Scarlett Johansson,"English (Dubbed in Telugu, Kannada, Hindi)",Marvel Studios
4,25,MOV026,Pailwaan,S. Krishna,Sports Action,2019.0,30.0,55.0,6.8,NaN,Sudeep,Aakanksha Singh,Kannada,RRR Motion Pictures

In [6]:
df[df.ReleaseYear.isna()]

,index,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
17,48,MOV049,U Turn,Pawan Kumar,Thriller,NaN,5.0,20.0,7.9,128.0,Shraddha Srinath,Dilip Raj,Kannada,PRK Productions

In [7]:
# release year is missing and its datatype shd not be float 

# i refered to the other dataset for the release year of the movie U turn and found that it was relesed in 2016 so i am filling it with this year

df['ReleaseYear']=df['ReleaseYear'].fillna(2016)

In [8]:
df['ReleaseYear']=df["ReleaseYear"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               18 non-null     int64
 1   MovieID             18 non-null     object
 2   Title               18 non-null     object
 3   Director            18 non-null     object
 4   Genre               18 non-null     object
 5   ReleaseYear         18 non-null     int64
 6   Budget (Crores)     10 non-null     float64
 7   BoxOffice (Crores)  10 non-null     float64
 8   Rating              17 non-null     float64
 9   Duration (minutes)  17 non-null     float64
 10  LeadActor           18 non-null     object
 11  LeadActress         18 non-null     object
 12  Language            18 non-null     object
 13  ProductionCompany   18 non-null     object
dtypes: float64(4), int64(2), object(8)
memory usage: 2.1+ KB

In [ ]:
# Budget and Boxeffice has 8 null values will fill that with mean

In [9]:
df[df['Budget (Crores)'].isna()]

,index,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
0,7,MOV008,Sarkar (Tamil),A. R. Murugadoss,Action Thriller,2005,NaN,NaN,7.5,173.0,Vijay,Keerthy Suresh,Tamil,Kalaignar TV
3,23,MOV024,Avengers: Endgame (Dubbed),"Anthony Russo, Joseph Russo",Superhero,2019,NaN,NaN,8.4,181.0,Robert Downey Jr.,Scarlett Johansson,"English (Dubbed in Telugu, Kannada, Hindi)",Marvel Studios
9,32,MOV033,96 (Kannada Dubbed),C. Premkumar,Romantic Drama,2019,NaN,NaN,7.9,158.0,Vijay Sethupathi,Trisha,Kannada (Dubbed from Tamil),Madras Enterprises
10,34,MOV035,Dabangg 3 (Dubbed),Prabhu Deva,Action Comedy,2019,NaN,NaN,5.8,159.0,Salman Khan,Sonakshi Sinha,Telugu (Dubbed from Hindi),S. K. Film Enterprises
11,36,MOV037,Shylock (Kannada Dubbed),Ajai Vasudev,Action Thriller,2020,NaN,NaN,6.8,164.0,Mammootty,Rajkiran,Kannada (Dubbed from Malayalam),Vrindaavan Films
12,37,MOV038,Love Aaj Kal (Dubbed),Imtiaz Ali,Romantic Drama,2020,NaN,NaN,4.4,141.0,Kartik Aaryan,Sara Ali Khan,Telugu (Dubbed from Hindi),Reliance Entertainment
13,38,MOV039,Forensic (Kannada Dubbed),"Akhil Paul, Anas Khan",Thriller,2020,NaN,NaN,6.9,129.0,Tovino Thomas,Mamta Mohandas,Kannada (Dubbed from Malayalam),Evil Eye Pictures
14,39,MOV040,Trance (Kannada Dubbed),Anwar Rasheed,Psychological Thriller,2020,NaN,NaN,7.1,162.0,Fahadh Faasil,Nazriya Nazim,Kannada (Dubbed from Malayalam),Dulquer Salmaan Productions

In [14]:
df['Budget (Crores)']=df['Budget (Crores)'].fillna(df["Budget (Crores)"].median())

In [13]:
df['BoxOffice (Crores)']=df['BoxOffice (Crores)'].fillna(df['BoxOffice (Crores)'].median())

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               18 non-null     int64
 1   MovieID             18 non-null     object
 2   Title               18 non-null     object
 3   Director            18 non-null     object
 4   Genre               18 non-null     object
 5   ReleaseYear         18 non-null     int64
 6   Budget (Crores)     18 non-null     float64
 7   BoxOffice (Crores)  18 non-null     float64
 8   Rating              17 non-null     float64
 9   Duration (minutes)  17 non-null     float64
 10  LeadActor           18 non-null     object
 11  LeadActress         18 non-null     object
 12  Language            18 non-null     object
 13  ProductionCompany   18 non-null     object
dtypes: float64(4), int64(2), object(8)
memory usage: 2.1+ KB

In [16]:
df[df['Rating'].isna()]

,index,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
7,30,MOV031,Saaho,Sujeeth,Action Thriller,2019,300.0,450.0,NaN,170.0,Prabhas,Shraddha Kapoor,"Telugu (Dubbed in Hindi, Kannada)",UV Creations

In [18]:
# i refered to  the bollywood dataset for the title sahoo and filling the null val with its rating here

df['Rating']=df['Rating'].fillna(6.5)

In [19]:
df[df['Duration (minutes)'].isna()]

,index,MovieID,Title,Director,Genre,ReleaseYear,Budget (Crores),BoxOffice (Crores),Rating,Duration (minutes),LeadActor,LeadActress,Language,ProductionCompany
4,25,MOV026,Pailwaan,S. Krishna,Sports Action,2019,30.0,55.0,6.8,NaN,Sudeep,Aakanksha Singh,Kannada,RRR Motion Pictures

In [20]:
df['Duration (minutes)']=df['Duration (minutes)'].fillna(166).astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               18 non-null     int64
 1   MovieID             18 non-null     object
 2   Title               18 non-null     object
 3   Director            18 non-null     object
 4   Genre               18 non-null     object
 5   ReleaseYear         18 non-null     int64
 6   Budget (Crores)     18 non-null     float64
 7   BoxOffice (Crores)  18 non-null     float64
 8   Rating              18 non-null     float64
 9   Duration (minutes)  18 non-null     int64
 10  LeadActor           18 non-null     object
 11  LeadActress         18 non-null     object
 12  Language            18 non-null     object
 13  ProductionCompany   18 non-null     object
dtypes: float64(3), int64(3), object(8)
memory usage: 2.1+ KB

Data is cleaned no missing values and inconsistency

In [21]:
df.to_excel('indian.xlsx',index=False)